---
AWSTemplateFormatVersion: 2010-09-09
Description: PEDL Template
Parameters:
  Keypair:
    Type: String
    Description: Keypair to SSH

  UserName:
    Type: String
    Description: The User Who Deployed the Stack

  MasterAmiId:
    Type: String
    Description: AMI Id for Master

  MasterInstanceType:
    Type: String
    Description: Instance Type of Master

  AgentAmiId:
    Type: String
    Description: AMI Id for Agent

  AgentInstanceType:
    Type: String
    Description: Instance Type of Agent

  UserAccessIngressCidr:
    Type: String
    Default: 0.0.0.0/0
    Description: User preferred CIDR block for Master UI and all SSH access

Resources:
  CheckpointBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub pedl-${UserName}-${AWS::Region}-${AWS::AccountId}

  MasterSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !GetAtt MasterSecurityGroup.GroupId
      DestinationSecurityGroupId: !GetAtt AgentSecurityGroup.GroupId
      FromPort: 0
      ToPort: 65535
      IpProtocol: tcp

  MasterSecurityGroupInternet:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !GetAtt MasterSecurityGroup.GroupId
      CidrIp: 0.0.0.0/0
      FromPort: 0
      ToPort: 65535
      IpProtocol: tcp

  MasterSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt MasterSecurityGroup.GroupId
      FromPort: 8080
      ToPort: 8080
      IpProtocol: tcp
      SourceSecurityGroupId: !GetAtt AgentSecurityGroup.GroupId

  MasterSecurityGroupIngressUI:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt MasterSecurityGroup.GroupId
      FromPort: 8080
      ToPort: 8080
      IpProtocol: tcp
      CidrIp: !Ref UserAccessIngressCidr

  MasterSSHIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt MasterSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: !Ref UserAccessIngressCidr

  AgentSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !GetAtt AgentSecurityGroup.GroupId
      CidrIp: 0.0.0.0/0
      FromPort: 0
      ToPort: 65535
      IpProtocol: tcp

  AgentSecurityGroupIngressMaster:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt AgentSecurityGroup.GroupId
      FromPort: 0
      ToPort: 65535
      IpProtocol: tcp
      SourceSecurityGroupId: !GetAtt MasterSecurityGroup.GroupId

  AgentSecurityGroupIngressAgent:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt AgentSecurityGroup.GroupId
      FromPort: 0
      ToPort: 65535
      IpProtocol: tcp
      SourceSecurityGroupId: !GetAtt AgentSecurityGroup.GroupId

  AgentSSHIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt AgentSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: !Ref UserAccessIngressCidr

  DatabaseEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !GetAtt DatabaseSecurityGroup.GroupId
      CidrIp: 0.0.0.0/0
      FromPort: 0
      ToPort: 65535
      IpProtocol: -1

  DatabaseIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt DatabaseSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !GetAtt MasterSecurityGroup.GroupId

  MasterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group For Master
      Tags:
        - Key: user
          Value: !Ref UserName

  AgentSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group For Agent
      Tags:
        - Key: user
          Value: !Ref UserName

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group For Database
      Tags:
        - Key: user
          Value: !Ref UserName

  Database:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineMode: serverless
      DatabaseName: pedl
      DBClusterParameterGroupName: 'default.aurora-postgresql10'
      MasterUsername: postgres
      MasterUserPassword: postgres
      Tags:
        - Key: user
          Value: !Ref UserName
      VpcSecurityGroupIds:
        - !GetAtt DatabaseSecurityGroup.GroupId

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /determined/pedl-${UserName}/journald

  LogPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref AgentRole
        - !Ref MasterRole
      PolicyName: agent-log-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
            Resource:
              - !Sub arn:aws:logs:*:*:log-group:/determined/pedl-${UserName}/journald,
              - !Sub arn:aws:logs:*:*:log-group:/determined/pedl-${UserName}/journald:log-stream:*

  MetricPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref AgentRole
        - !Ref MasterRole
      PolicyName: agent-metric-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - cloudwatch:PutMetricData
            Effect: Allow
            Resource: "*"

  AgentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: agent-s3-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: "*"
        - PolicyName: pedl-ec2
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                Resource: "*"

  AgentInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref AgentRole

  MasterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: pedl-agent-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:TerminateInstances
                  - ec2:CreateTags
                  - ec2:RunInstances
                Resource: "*"
        - PolicyName: pass-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt AgentRole.Arn
      Tags:
        - Key: user
          Value: !Ref UserName

  MasterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MasterRole

  MasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref MasterInstanceType
      ImageId: !Ref MasterAmiId
      KeyName: !Ref Keypair
      IamInstanceProfile: !Ref MasterInstanceProfile
      SecurityGroupIds:
        - !Ref MasterSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 200
            VolumeType: gp2
      UserData:
        Fn::Base64: !Sub |
          Content-Type: multipart/mixed; boundary="//"
          MIME-Version: 1.0

          --//
          Content-Type: text/cloud-config; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="cloud-config.txt"

          #cloud-config
          cloud_final_modules:
          - [scripts-user, always]

          --//
          Content-Type: text/x-shellscript; charset="us-ascii"
          MIME-Version: 1.0
          Content-Transfer-Encoding: 7bit
          Content-Disposition: attachment; filename="userdata.txt"

          #!/bin/bash

          cat << EOF > /tmp/master.yaml
          checkpoint_storage:
            type: s3
            bucket: ${CheckpointBucket}
            save_experiment_best: 0
            save_trial_best: 1
            save_trial_latest: 1

          provisioner:
            agent_docker_network: pedl
            iam_instance_profile_arn: ${AgentInstanceProfile.Arn}
            image_id: ${AgentAmiId}
            instance_name: pedl-agent-${UserName}
            instance_type: ${AgentInstanceType}
            master_url: http://local-ipv4:8080
            max_idle_agent_period: 5m
            max_instances: 5
            network_interface:
              public_ip: true
              security_group_id: ${AgentSecurityGroup.GroupId}
            provider: aws
            root_volume_size: 200
            ssh_key_name: ${Keypair}
            startup_script: |
              cat << EOF > /tmp/journald-cloudwatch.conf
              log_group = "/determined/pedl-${UserName}/journald"
              EOF

              rm /etc/journald-cloudwatch.conf
              mv /tmp/journald-cloudwatch.conf /etc/journald-cloudwatch.conf
              systemctl restart journald-cloudwatch
            tag_key: pedl-${UserName}
            tag_value: pedl-${UserName}-agent
          EOF

          rm /usr/local/pedl/etc/master.yaml
          mv /tmp/master.yaml /usr/local/pedl/etc/master.yaml

          cat << EOF > /tmp/override.conf
          [Service]
          Environment="PEDL_DB_HOSTNAME=${Database.Endpoint.Address}"
          Environment="PEDL_DB_USER=postgres"
          Environment="PEDL_DB_NAME=pedl"
          Environment="PEDL_DB_PASSWORD=postgres"
          EOF

          mkdir /etc/systemd/system/pedl-master.service.d/
          mv /tmp/override.conf /etc/systemd/system/pedl-master.service.d/override.conf

          cat << EOF > /tmp/journald-cloudwatch.conf
          log_group = "/determined/pedl-${UserName}/journald"
          field_length = 1000
          EOF

          rm /etc/journald-cloudwatch.conf
          mv /tmp/journald-cloudwatch.conf /etc/journald-cloudwatch.conf
          systemctl restart journald-cloudwatch

          cd /usr/local/pedl/
          make enable-master
          --//
      Tags:
        - Key: user
          Value: !Ref UserName
        - Key: Name
          Value: !Sub pedl-${UserName}-master

Outputs:
  MasterId:
    Description: Id of Master Agent
    Value: !Ref MasterInstance

  MasterPublicIp:
    Description: Public IP of Master Agent
    Value: !GetAtt MasterInstance.PublicIp

  MasterSecurityGroupId:
    Description: Id of Master Security Group
    Value: !GetAtt MasterSecurityGroup.GroupId

  AgentSecurityGroupId:
    Description: Id of Agent Security Group
    Value: !GetAtt AgentSecurityGroup.GroupId

  AgentInstanceProfile:
    Description: Instance Profile for Agent
    Value: !GetAtt AgentInstanceProfile.Arn

  CheckpointBucket:
    Description: S3 Bucket for checkpoints
    Value: !Ref CheckpointBucket


